### ISSUE TITLE
Feature request: more visibility of internal status

### ISSUE THREAD

**Issue by mgravell** [bretcope/BosunReporter.NET#17]
It is very hard to know whether it is working, as there are no API hooks that allow you to see metadata such as "last upload", "number of uploads", "number of metrics", or whatever - I don't know quite what *should* be exposed, but it would be good to have some mechanism to provide high level info; heck, just a `ToString()` status might be enough

**Comment by bretcope** [comment]
This shouldn't be too hard. I basically need to provide an API for the sorts of data I'm outputting to the console in debug builds.

**Comment by bretcope** [comment]
Sorry this took me a while to get to. I've been effectively gone for 5 of the past 9 weeks, so it was hard to prioritize. Now I'm back to a normal person schedule.

Properties added to `MetricsCollector`:

* __TotalMetricsPosted__: Total number of data points successfully sent fo Bosun.
* __PostSuccessCount__: The number of times an HTTP POST to Bosun's /api/put endpoint has succeeded.
* __PostFailCount__: Attempts which have failed.
* __LastSerializationInfo__: An `AfterSerializationInfo` object which describes when the last serialization took place, how long it took, and how many data points were serialized.
* __LastPostInfo__: An `AfterPostInfo` object which describes when the last POST to Bosun occurred, how long it took, how many data points were sent, whether it was successful, and the exception which occurred if it was not successful.

Events added:

* __AfterSerialization__: Allows you to subscribe to receive `AfterSerializationInfo` objects after every serialization event.
* __AfterPost__: Same idea for `AfterPostInfo` objects on POST events.

I think these changes should satisfy your request, but if not, let me know. I'm also going to add a way to automatically send to Bosun a gauge of how many data points were sent, but that's a slightly different issue.
