### ISSUE TITLE
Add IMetricGroup with type parameter variance

### ISSUE THREAD

**Issue by couchand** [bretcope/BosunReporter.NET#22]
I've been taking advantage of the flexibility of passing around `IDoubleGauge`s to keep the specific choice of gauge as configuration.  Now, I'd like the ability to do the same with `MetricGroup`s of them.  This will require creating an interface `IMetricGroup`, since variant type annotations can only be applied to interfaces, not classes.

Here are the expected variances of the type parameters:

  * `TMetric` is clearly covariant, since you are using it for output.  Namely, you want to be able to perform this assignment legally:

        IMetricGroup<bool, IDoubleGauge> group = GetMetricGroup<bool, EventGauge>(...);

  * The other type parameters are *probably* contravariant, since they are used as inputs.  I believe you would like the following assignment to be legal:

        IMetricGroup<short, EventGauge> group = GetMetricGroup<int, EventGauge>(...);

The reasoning in the latter case can be considered like this: later calls to the `group` variable will only ever try to produce a new metric with a tag value of the derived type, but the `MetricGroup` can handle anything that's of the base type.  I could also see the case made that it should just be invariant.

There's a big caveat to all of this: `MetricGroup` has mutable state.  That means, if you cast to a group type with a more generic `TMetric` and then try to add an incompatible metric you'll get a runtime type error.  Fortunately, the actual creation of the metric added is handled by the factory, which is type-specific, so I believe we're golden.

Adding this interface would lock in two specific aspects of the `MetricGroup` API:

  * we couldn't add a `TMetric` as an input parameter to a method on `MetricGroup` (e.g. `void AddCustom(T1 key, TMetric metric)`)
  * we couldn't add a method that returns values of the other parameter types  (e.g. `IEnumerable<T1> GetKeys()`)

The first point seems like a reasonable limitation, but I could see how the second point is too limiting.  That's why it might be useful to leave the other parameters as invariant.  Also, I can't think of a great use case for really needing contravariance on those parameters, whereas for the covariance of `TMetric` the value is obvious.

This may be a little bit of effort, but I think it's worth it to promote `MetricGroup` to the same level of flexibility that the first-level gauges and counters have.  Also I'm totally willing to hack at it, as long as the idea seems reasonable.

some docs
  * [Defining Variant Generic Interfaces and Delegates](https://msdn.microsoft.com/en-us/library/dd799517%28v=vs.110%29.aspx#DefiningVariantTypeParameters)
  * [Variance in Generic Interfaces](https://msdn.microsoft.com/en-us/library/dd233059%28v=vs.110%29.aspx)

**Comment by couchand** [comment]
Hmm.. I think I might have gotten the variance wrong in the other type parameter case.  The uncertainty about that is yet another reason to just leave it as invariant.

**Comment by bretcope** [comment]
I have no interest in making any of the type parameters contravariant. That strikes me as having a very weak use case which is more likely to get you in trouble than actually solve any problem.

`TMetric` could be covariant, but you're going to have to convince me with compelling real-world examples, not just a statement of "whereas for the covariance of TMetric the value is obvious." It's not free to convert it. It means extra template code to maintenance, and creating an interface will force all of the instance methods to become virtual which means a v-table lookup, plus the JIT won't be able to inline those methods anymore.

Part of the philosophy behind the metric groups was to add as little performance overhead as possible over declaring all the metrics as variables. I'm pretty sensitive about doing anything which would hurt that. I actually have a few more things left to improve on that front.

I actually tend to think it's a bad idea to be passing around metric groups at all. That means you're pushing the decision of how to tag a metric off to another part of the code, and if that's the case, you're probably better off just declaring the metric group in that part of the code.

**Comment by couchand** [comment]
I guess I sort of glossed over my use case at the beginning, so I can see how that wasn't clear.  The specific usage is for a generalized api metrics handler -- each of the various apis has metrics in common, such as count of requests and timing of response.  They are also tagged similarly in each case.  However, depending on the volume of traffic to each one, we may or may not be aggregating the results.  So we want a factory method that can do this:

    public IMetricGroup<MyEnum, IDoubleGauge> GetResponseGroup(bool aggregateCounts = false)
    {
        if (aggregateCounts)
        {
            return collector.GetMetricGroup<MyEnum, MyAggregateGauge>(...);
        }
        else
        {
            return collector.GetMetricGroup<MyEnum, MyEventGauge>(...);
        }
    }

And, since both gauges implement `IDoubleGauge` this would work nicely, given covariance.

I suppose its possible the v-table indirection could be a significant factor at the loads you guys are doing, but in nearly every case I'd expect it to be insignificant.  If multiple metrics are going to be tagged with the same mechanism, it seems like DRY would suggest we should tag them with the same code if possible.  All it comes down to is decoupling the tagging from the aggregating.

**Comment by bretcope** [comment]
After giving this much thought, I'm at least willing to try this, with one caveat: I want to see some realistic perf data. I expect there will be some drop in performance, but not huge. But I'd like to know what that trade off is, rather than just accepting it blind.

I can help you devise a benchmarking strategy if you want, but I'm leaving it up to you to do the work, since you're the one who wants the feature.

**Comment by couchand** [comment]
Well, I noticed an issue that will probably make this a no-go.  The `MetricGroup` metric type parameter is limited to a subclass of `BosunMetric` to clarify the intended use, but the consumer of the metrics really just wants one of the interfaces such as an `IDoubleGauge` to be able to `Record` on.  Since `IDoubleGauge` isn't a `BosunMetric`, it's not a valid type parameter, and thus the propsed type `IMetricGroup<MyEnum, IDoubleGauge>` would be illegal unless the `IMetricGroup` has a different type constraint than the `MetricGroup`, which seems like a bad idea.

**Comment by bretcope** [comment]
Oh, yeah, that's a good point. I don't really want to go down that mess of a road.
