### ISSUE TITLE
Question about the limits of bosun

### ISSUE THREAD

**Issue by lanzelot1989** [bretcope/BosunReporter.NET#26]
Hi!

Are there people who use bosun and BosunReporter.NET in production to measure app metrics like service or page calls.

I am very interested in the kind of throughput that people are able to achieve.

So far, I only got the information that StackExchange's setup can cope with 15k entries per seconds which amount to about 3GB of data a day.

**Comment by bretcope** [comment]
We have lots of metrics which are measured on every page load. These are generally aggregated by reporting intervals though (BosunReporter defaults to 30 seconds). For example, when we measure response times, we don't send one data point per page load. We send a set of aggregates (min, median, max, average, etc) every 30 seconds.

I think your question might be more of a [Bosun](https://github.com/bosun-monitor/bosun) question than a BosunReporter question though. Feel free to ask for more information over there. If you have specific questions on how to use this library to send data, then ask that here.

**Comment by lanzelot1989** [comment]
Hi @bretcope,

thanks for your input and redirecting me to the right place.
